# Generated by Django 4.0.3 on 2022-07-30 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('speciality', models.CharField(blank=True, max_length=500, null=True)),
                ('awards', models.CharField(blank=True, max_length=500, null=True)),
                ('medical_id_proof', models.FileField(blank=True, null=True, upload_to='counselor/medical_id')),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('fees', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_counselor',
            field=models.BooleanField(default=False, verbose_name='counselor status'),
        ),
    ]
