# Generated by Django 4.0.3 on 2022-08-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_student_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='latitude',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='counselor',
            name='longitude',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
