# Generated by Django 4.0.3 on 2022-08-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_counselor_latitude_counselor_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
