# Generated by Django 4.0.3 on 2022-08-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_counselor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='division',
            field=models.CharField(default='B', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='std',
            field=models.CharField(default='7', max_length=10),
            preserve_default=False,
        ),
    ]
