# Generated by Django 4.0.3 on 2022-08-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_student_division_student_std'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='standard_HI',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='year',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='std_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
