# Generated by Django 4.0.3 on 2022-08-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_school_standard_hi_school_year_student_std_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='std_id',
        ),
    ]
