# Generated by Django 4.0.3 on 2022-08-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_student_std_id_alter_school_standard_hi'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rewards',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
