# Generated by Django 4.0.3 on 2022-03-23 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.school')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('english', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
