# Generated by Django 4.0.3 on 2022-08-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academics',
            name='email',
        ),
        migrations.AddField(
            model_name='academics',
            name='attentiveness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academics',
            name='confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academics',
            name='creativity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academics',
            name='geo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academics',
            name='hindi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academics',
            name='history',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academics',
            name='interactivity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academics',
            name='maths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academics',
            name='obedience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academics',
            name='participation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academics',
            name='percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academics',
            name='science',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academics',
            name='social_relationship',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academics',
            name='standard',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academics',
            name='timely_submissions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
