# Generated by Django 4.0.3 on 2022-08-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0002_remove_academics_email_academics_attentiveness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='attentiveness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academics',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academics',
            name='creativity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academics',
            name='english',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academics',
            name='geo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academics',
            name='hindi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academics',
            name='history',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academics',
            name='interactivity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academics',
            name='maths',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academics',
            name='obedience',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academics',
            name='participation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academics',
            name='percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academics',
            name='science',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academics',
            name='social_relationship',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academics',
            name='timely_submissions',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
