# Generated by Django 4.0.3 on 2022-08-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0003_alter_academics_attentiveness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academics',
            name='division',
            field=models.CharField(default='B', max_length=3),
            preserve_default=False,
        ),
    ]
