# Generated by Django 4.0.3 on 2022-08-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0004_academics_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_weights', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='academics',
            name='roll_no',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
