# Generated by Django 4.0.3 on 2022-08-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0005_weights_alter_academics_roll_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weights',
        ),
    ]
