# Generated by Django 4.0.3 on 2022-08-25 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_school_standard_hi_school_year_student_std_id'),
        ('Analytics', '0006_delete_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='academics',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.student'),
        ),
        migrations.AlterField(
            model_name='academics',
            name='roll_no',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
