<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-03-23 17:49

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 4.0.3 on 2022-03-23 17:50

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
>>>>>>> 0fec730f3b6ac471985f786d5acf5d4bd4d8c603


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('profiles', '0002_school_happiness_score'),
=======
        ('profiles', '0001_initial'),
>>>>>>> 0fec730f3b6ac471985f786d5acf5d4bd4d8c603
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('levelc', models.IntegerField()),
                ('env', models.IntegerField()),
                ('teachersc', models.IntegerField()),
                ('prevdisc', models.IntegerField()),
                ('fecilities', models.IntegerField()),
                ('timetable', models.IntegerField()),
                ('grpwork', models.IntegerField()),
                ('mentalhlth', models.IntegerField()),
                ('sportart', models.IntegerField()),
                ('solveprob', models.IntegerField()),
                ('creativecourse', models.IntegerField()),
                ('foconindv', models.IntegerField()),
                ('mannlearn', models.IntegerField()),
                ('courserele', models.IntegerField()),
                ('issuesofconc', models.IntegerField()),
                ('aresolved', models.IntegerField()),
                ('others', models.CharField(max_length=1000)),
=======
                ('levelc', models.IntegerField(max_length=100)),
                ('disc_content', models.CharField(max_length=5000)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='disc_title', unique=True)),
>>>>>>> 0fec730f3b6ac471985f786d5acf5d4bd4d8c603
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.school')),
            ],
        ),
    ]
