# Generated by Django 4.0.3 on 2022-08-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='std',
            field=models.CharField(default='1', max_length=3),
            preserve_default=False,
        ),
    ]
