# Generated by Django 4.0.3 on 2022-08-25 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_student_std_id_alter_school_standard_hi'),
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.student'),
        ),
    ]
