# Generated by Django 4.0.3 on 2022-08-25 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_student_std_id_alter_school_standard_hi'),
        ('suggestions', '0002_data_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelc', models.IntegerField()),
                ('life_skills', models.IntegerField()),
                ('exam_in_acc_course', models.IntegerField()),
                ('innovation_time', models.IntegerField()),
                ('support', models.IntegerField()),
                ('anxiety', models.IntegerField()),
                ('alienated', models.IntegerField()),
                ('family_burden', models.IntegerField()),
                ('insecurity', models.IntegerField()),
                ('fundamental_rules', models.IntegerField()),
                ('others', models.TextField()),
                ('solution', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.student')),
            ],
        ),
        migrations.CreateModel(
            name='Data2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelc', models.IntegerField()),
                ('extra_curr', models.IntegerField()),
                ('course_rev', models.IntegerField()),
                ('violence', models.IntegerField()),
                ('teachers', models.IntegerField()),
                ('anxiety', models.IntegerField()),
                ('environment', models.IntegerField()),
                ('grpwork', models.IntegerField()),
                ('secure', models.IntegerField()),
                ('socially_active', models.IntegerField()),
                ('others', models.TextField()),
                ('solution', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.student')),
            ],
        ),
        migrations.CreateModel(
            name='Data1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playtime', models.IntegerField()),
                ('extra_curr', models.IntegerField()),
                ('difficult', models.IntegerField()),
                ('materials', models.IntegerField()),
                ('fear', models.IntegerField()),
                ('like_sch', models.IntegerField()),
                ('environment', models.IntegerField()),
                ('like_friends', models.IntegerField()),
                ('others', models.TextField()),
                ('solution', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.student')),
            ],
        ),
    ]
