# Generated by Django 4.0.3 on 2022-08-06 06:45

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forumpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(blank=True, max_length=500, null=True), unique=True),
        ),
    ]
