# Generated by Django 4.0.3 on 2022-08-06 06:46

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_forumpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
