# Generated by Django 4.0.3 on 2022-08-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_forumpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
