# Generated by Django 4.0.3 on 2022-08-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Councellor',
            new_name='CounselorRequest',
        ),
    ]
