# Generated by Django 4.0.3 on 2022-08-09 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_student_pincode'),
        ('counsellor', '0002_rename_councellor_counselorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorrequest',
            name='assigned_counselor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.counselor'),
        ),
    ]
